### ISSUE TITLE
Update to iOS 5.1

### ISSUE THREAD

**Issue by shortstuffsushi** [grgcombs/iOS-Shapefile#1]
Hey,

I would like to make use of this project, but would it be possible for you to bring it up to a more recent version of iOS?

**Comment by grgcombs** [comment]
This comes about 4 years late, but this issue is fixed with 2c24010c03337dcebc23baa629afa55de4d16e93

**Comment by grgcombs** [comment]
Also, I offer my apologies for missing this thread for so long!

**Comment by shortstuffsushi** [comment]
Hahaha this is great! Thank you for getting to this, though at this point I don't even remember what I was planning to use this library for ;)
